//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int role { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public int seria { get; set; }
        public int number { get; set; }
        public System.DateTime birthday { get; set; }
        public Nullable<System.DateTime> enter { get; set; }
        public Nullable<int> statys { get; set; }
        public int gender { get; set; }
    
        public virtual gender gender1 { get; set; }
        public virtual role role1 { get; set; }
        public virtual statys statys1 { get; set; }
    }
}
